name: Update Dependencies

env:
  NODE_VERSION: 20.12.1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update:
    name: Update all dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Update dependencies
        run: npx npm-check-updates --target minor -u

      - name: Delete node modules and lock file
        run: rm -Rf node_modules package-lock.json

      - name: Reinstall dependencies
        run: npm install

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTIONS_GITHUB_PAT }}
          commit-message: 'build: update dependencies to the latest version'
          title: Update dependencies to the latest version
